#!/bin/sh

# Export the required environment variables.
export __NV_PRIME_RENDER_OFFLOAD='1'
export __GLX_VENDOR_LIBRARY_NAME='nvidia'
export __VK_LAYER_NV_optimus='NVIDIA_only'

# Execute the program/application/binary supplied as the argument.
# exec $@
# exec "$@"
# exec "${@}"
exec ${@}
# exec "$@"
