#!/bin/sh

# Exit on any error.
# Exit if any unset variable is used/referenced.
set -eu

# Check if a signing key has been generated by the 'akmods' service.
echo "Checking if a signing key has been generated by the 'akmods' service as '/etc/pki/akmods/certs/public_key.der'."
if sudo test -f '/etc/pki/akmods/certs/public_key.der'; then

  echo 'Signing key found.'

# Otherwise.
else

  # Generate a signing key.
  echo "Generating a new signing key as '/etc/pki/akmods/certs/public_key.der'."
  sudo kmodgenca -a

fi

echo 'Importing the signing key into the MOK database.'
echo 'You will be prompted to enter a password for the same.'
echo 'Please set a strong password and remember it, as it will be needed to enroll the key into the MOK database after rebooting.'
sudo mokutil --import '/etc/pki/akmods/certs/public_key.der'

echo "Please reboot your system now."

# Exit with a successful error code.
exit 0
