#!/bin/sh

# Exit on any error.
# Exit if any unset variable is used/referenced.
set -eu

# Check if the script is not running as 'root'.
if [ "$(id -u)" -ne 0 ]; then

  echo "Script is running as '$(whoami)', not 'root'."
  echo "Attempting to switch to 'root'."

  # Re-execute this script as 'root'.
  exec sudo "$0" "$@"

  # Due to the 'exec' command above, the below lines of code will not execute if the script succeeds running as 'root'.
  echo "Failed to switch to the 'root' user."
  exit 1

fi

# Check if exactly one argument was passed.
if [ "$#" -ne 1 ]; then

  # Print an error and exit.
  echo 'Usage: ./setup-secure-boot <phase-1> OR <phase-2>'
  exit 1

fi

# Check if the argument is 'phase-1'.
if [ "${1}" = 'phase-1' ]; then

  # Install the required packages.
  echo 'Installing the required packages.'
  dnf install --refresh --offline --assumeyes kmodtool akmods mokutil openssl

  echo 'It is now strongly recommended to reboot using the command below'
  echo "'sudo dnf offline reboot'"

  echo "After rebooting, please run this same script with the only argument as 'phase-2'."

# Check if the argument is 'phase-2'.
elif [ "${1}" = 'phase-2' ]; then

  # Check if a signing key has been generated by the 'akmods' service.
  echo "Checking if a signing key has been generated by the 'akmods' service as '/etc/pki/akmods/certs/public_key.der'."
  if [ -f '/etc/pki/akmods/certs/public_key.der' ]; then

    echo 'Signing key found.'

  # Otherwise.
  else

    # Generate a signing key.
    echo "Generating a new signing key as '/etc/pki/akmods/certs/public_key.der'."
    kmodgenca -a 

  fi

  echo 'Importing the signing key into the MOK database.'
  echo 'You will be prompted to enter a password for the same.'
  echo 'Please set a strong password and remember it, as it will be needed to enroll the key into the MOK database after rebooting.'
  mokutil --import '/etc/pki/akmods/certs/public_key.der'

  echo "Please reboot your system now."

else

  # Print an error and exit.
  echo 'Usage: ./setup-secure-boot <phase-1> OR <phase-2>'
  exit 1

fi
